/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\TEST\Documents\C\GameBoy\Projects\MyDinoGame v2\src\Background\Background\Tiles\GameTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define BackgroundWidth 40
#define BackgroundHeight 18
#define BackgroundBank 0

extern unsigned char Background[];

/* End of BACKGROUND.H */
